// Code generated by sqlc. DO NOT EDIT.
// source: equipment.sql

package db

import (
	"context"
	"database/sql"
)

const createEquipment = `-- name: CreateEquipment :one
INSERT INTO equipment (
    model_number,
    description,
    location,
    parent,
    powered_from,
    controlled_from
    ) VALUES (
    $1, $2, $3, $4, $5, $6
    ) RETURNING id, model_number, description, created_at, location, parent, powered_from, controlled_from
`

type CreateEquipmentParams struct {
	ModelNumber    string        `json:"model_number"`
	Description    string        `json:"description"`
	Location       int64         `json:"location"`
	Parent         sql.NullInt64 `json:"parent"`
	PoweredFrom    sql.NullInt64 `json:"powered_from"`
	ControlledFrom sql.NullInt64 `json:"controlled_from"`
}

func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRowContext(ctx, createEquipment,
		arg.ModelNumber,
		arg.Description,
		arg.Location,
		arg.Parent,
		arg.PoweredFrom,
		arg.ControlledFrom,
	)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.ModelNumber,
		&i.Description,
		&i.CreatedAt,
		&i.Location,
		&i.Parent,
		&i.PoweredFrom,
		&i.ControlledFrom,
	)
	return i, err
}

const deleteEquipment = `-- name: DeleteEquipment :exec
DELETE FROM equipment 
WHERE id = $1
`

func (q *Queries) DeleteEquipment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEquipment, id)
	return err
}

const getEquipment = `-- name: GetEquipment :one
SELECT id, model_number, description, created_at, location, parent, powered_from, controlled_from FROM equipment WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEquipment(ctx context.Context, id int64) (Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipment, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.ModelNumber,
		&i.Description,
		&i.CreatedAt,
		&i.Location,
		&i.Parent,
		&i.PoweredFrom,
		&i.ControlledFrom,
	)
	return i, err
}

const listEquipment = `-- name: ListEquipment :many
SELECT id, model_number, description, created_at, location, parent, powered_from, controlled_from FROM equipment
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListEquipmentParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEquipment(ctx context.Context, arg ListEquipmentParams) ([]Equipment, error) {
	rows, err := q.db.QueryContext(ctx, listEquipment, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.ModelNumber,
			&i.Description,
			&i.CreatedAt,
			&i.Location,
			&i.Parent,
			&i.PoweredFrom,
			&i.ControlledFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipment = `-- name: UpdateEquipment :exec
UPDATE equipment 
SET
    model_number = $1,
    description = $2,
    location = $3,
    parent = $4,
    powered_from = $5,
    controlled_from = $6
WHERE id = $7
RETURNING id, model_number, description, created_at, location, parent, powered_from, controlled_from
`

type UpdateEquipmentParams struct {
	ModelNumber    string        `json:"model_number"`
	Description    string        `json:"description"`
	Location       int64         `json:"location"`
	Parent         sql.NullInt64 `json:"parent"`
	PoweredFrom    sql.NullInt64 `json:"powered_from"`
	ControlledFrom sql.NullInt64 `json:"controlled_from"`
	ID             int64         `json:"id"`
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) error {
	_, err := q.db.ExecContext(ctx, updateEquipment,
		arg.ModelNumber,
		arg.Description,
		arg.Location,
		arg.Parent,
		arg.PoweredFrom,
		arg.ControlledFrom,
		arg.ID,
	)
	return err
}
