// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Equipment struct {
	ID             int64         `json:"id"`
	ModelNumber    string        `json:"model_number"`
	Description    string        `json:"description"`
	CreatedAt      time.Time     `json:"created_at"`
	Location       int64         `json:"location"`
	Parent         sql.NullInt64 `json:"parent"`
	PoweredFrom    sql.NullInt64 `json:"powered_from"`
	ControlledFrom sql.NullInt64 `json:"controlled_from"`
}

type Location struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	InsideOf    sql.NullInt64  `json:"inside_of"`
}
